export const DEFAULT_GARDEN_SLOTS = {
    SG1: "sg1",
    SG2: "sg2",
    SG3: "sg3",
    SG4: "sg4",
    SG5: "sg5",
    SG6: "sg6",
    SG7: "sg7",
    SG8: "sg8",
    SG9: "sg9",
    SG10: "sg10",
    SG11: "sg11",
    SG12: "sg12",
    SG13: "sg13",
    SG14: "sg14",
    SG15: "sg15",
    SG16: "sg16",
    SG17: "sg17",
    SG18: "sg18",
    SG19: "sg19",
    SG20: "sg20",
    SG21: "sg21",
    SG22: "sg22",
    SG23: "sg23",
    SG24: "sg24",

    SL1: "sl1",
    SL2: "sl2",
    SL3: "sl3",
    SL4: "sl4",
};

export const INIT_GARDEN_SLOT_VALUES = {
    [DEFAULT_GARDEN_SLOTS.SG1]: null,
    [DEFAULT_GARDEN_SLOTS.SG2]: null,
    [DEFAULT_GARDEN_SLOTS.SG3]: null,
    [DEFAULT_GARDEN_SLOTS.SG4]: null,
    [DEFAULT_GARDEN_SLOTS.SG5]: null,
    [DEFAULT_GARDEN_SLOTS.SG6]: null,
    [DEFAULT_GARDEN_SLOTS.SG7]: null,
    [DEFAULT_GARDEN_SLOTS.SG8]: null,
    [DEFAULT_GARDEN_SLOTS.SG9]: null,
    [DEFAULT_GARDEN_SLOTS.SG10]: null,
    [DEFAULT_GARDEN_SLOTS.SG11]: null,
    [DEFAULT_GARDEN_SLOTS.SG12]: null,
    [DEFAULT_GARDEN_SLOTS.SG13]: null,
    [DEFAULT_GARDEN_SLOTS.SG14]: null,
    [DEFAULT_GARDEN_SLOTS.SG15]: null,
    [DEFAULT_GARDEN_SLOTS.SG16]: null,
    [DEFAULT_GARDEN_SLOTS.SG17]: null,
    [DEFAULT_GARDEN_SLOTS.SG18]: null,
    [DEFAULT_GARDEN_SLOTS.SG19]: null,
    [DEFAULT_GARDEN_SLOTS.SG20]: null,
    [DEFAULT_GARDEN_SLOTS.SG21]: null,
    [DEFAULT_GARDEN_SLOTS.SG22]: null,
    [DEFAULT_GARDEN_SLOTS.SG23]: null,
    [DEFAULT_GARDEN_SLOTS.SG24]: null,
    [DEFAULT_GARDEN_SLOTS.SL1]: null,
    [DEFAULT_GARDEN_SLOTS.SL2]: null,
    [DEFAULT_GARDEN_SLOTS.SL3]: null,
    [DEFAULT_GARDEN_SLOTS.SL4]: null,
};
